export const CIVILIZATIONS = [
  {
    id: "aurelia",
    name: "Aurelian Republic",
    region: "Europe",
    capital: "Aurelia",
    title: "The eagle rises",
    description:
      "From fertile valleys and marble cities, disciplined legions forge a new republic.",
    bonus: "Legion discipline · +15% infantry defense",
    color: "#76a9b6",
    symbol: "eagle",
  },
  {
    id: "shen",
    name: "Shen Dynasty",
    region: "Asia",
    capital: "Jadehaven",
    title: "Beneath the jade heavens",
    description:
      "Mountain sanctuaries and terraced fields sustain a kingdom of patient strategists.",
    bonus: "Bountiful harvest · +20% food production",
    color: "#96b79a",
    symbol: "mountain",
  },
  {
    id: "ashur",
    name: "Ashuran Dominion",
    region: "Middle East",
    capital: "Sunspire",
    title: "Where the rivers meet",
    description:
      "Caravan cities and sun-baked citadels command the ancient roads of the desert.",
    bonus: "Golden road · +25% gold production",
    color: "#d5ac68",
    symbol: "sun",
  },
];
export const BUILDINGS = [
  {
    id: "farm",
    name: "Farm",
    description: "Fertile fields feed your growing empire.",
    cost: { wood: 80 },
    time: 8,
    hp: 300,
    production: { food: 5 },
    icon: "Wheat",
  },
  {
    id: "lumber",
    name: "Lumber Mill",
    description: "Turn the forests into the foundations of a civilization.",
    cost: { wood: 100, stone: 30 },
    time: 10,
    hp: 400,
    production: { wood: 4 },
    icon: "Trees",
  },
  {
    id: "quarry",
    name: "Stone Quarry",
    description: "Cut stone for walls, monuments and fortresses.",
    cost: { wood: 130, food: 40 },
    time: 12,
    hp: 500,
    production: { stone: 3 },
    icon: "Mountain",
  },
  {
    id: "goldmine",
    name: "Gold Mine",
    description: "Extract the wealth hidden beneath the hills.",
    cost: { wood: 150, stone: 80 },
    time: 14,
    hp: 450,
    production: { gold: 2 },
    icon: "Gem",
  },
  {
    id: "barracks",
    name: "Barracks",
    description: "Recruit and train disciplined frontline soldiers.",
    cost: { wood: 180, stone: 80 },
    time: 12,
    hp: 850,
    icon: "Swords",
  },
  {
    id: "archery",
    name: "Archery Range",
    description: "Unlock archers and crossbow specialists.",
    cost: { wood: 200, gold: 60 },
    time: 14,
    hp: 650,
    icon: "Crosshair",
  },
  {
    id: "stable",
    name: "Stable",
    description: "Raise cavalry to outflank the enemy.",
    cost: { wood: 220, food: 100 },
    time: 18,
    hp: 750,
    icon: "Flag",
  },
  {
    id: "siege",
    name: "Siege Workshop",
    description: "Build engines capable of breaking city defenses.",
    cost: { wood: 320, stone: 150, gold: 120 },
    time: 22,
    hp: 950,
    requires: "engineering",
    icon: "Hammer",
  },
  {
    id: "blacksmith",
    name: "Blacksmith",
    description: "A forge for stronger weapons and armor.",
    cost: { wood: 160, stone: 90 },
    time: 14,
    hp: 650,
    icon: "Anvil",
  },
  {
    id: "market",
    name: "Market",
    description: "Exchange a hundred wood for sixty gold.",
    cost: { wood: 180, stone: 50 },
    time: 12,
    hp: 650,
    production: { gold: 1 },
    icon: "Store",
  },
  {
    id: "wall",
    name: "Defensive Wall",
    description: "Stone fortifications hold back hostile armies.",
    cost: { stone: 180, wood: 40 },
    time: 10,
    hp: 1800,
    icon: "BrickWall",
  },
  {
    id: "tower",
    name: "Watchtower",
    description: "Fires on nearby enemies. Guards the capital.",
    cost: { stone: 160, wood: 80 },
    time: 16,
    hp: 1100,
    icon: "Castle",
  },
  {
    id: "academy",
    name: "Military Academy",
    description: "Allows recruitment of elite commanders.",
    cost: { wood: 220, stone: 200, gold: 160 },
    time: 25,
    hp: 1000,
    requires: "tactics",
    icon: "GraduationCap",
  },
  {
    id: "research",
    name: "Research Center",
    description: "A home for scholars and new ideas.",
    cost: { wood: 180, stone: 120, gold: 80 },
    time: 18,
    hp: 750,
    icon: "BookOpen",
  },
  {
    id: "storage",
    name: "Storage Building",
    description: "Increases storage by 2,000 and population by 20.",
    cost: { wood: 140, stone: 60 },
    time: 12,
    hp: 650,
    icon: "Package",
  },
  {
    id: "harbor",
    name: "Harbor",
    description: "Riverside commerce brings gold to your city.",
    cost: { wood: 250, stone: 120 },
    time: 20,
    hp: 900,
    production: { gold: 3 },
    nearWater: true,
    icon: "Ship",
  },
  {
    id: "towncenter",
    name: "Town Center",
    description: "The beating heart of a settlement. +20 population.",
    cost: { wood: 300, stone: 250, gold: 100 },
    time: 30,
    hp: 2000,
    production: { food: 2, wood: 2, stone: 1, gold: 1 },
    icon: "Landmark",
  },
  {
    id: "palace",
    name: "Capital Palace",
    description: "A lasting monument to your growing empire.",
    cost: { wood: 500, stone: 600, gold: 400 },
    time: 40,
    hp: 3000,
    requires: "masonry",
    icon: "Crown",
  },
];
export const TECHNOLOGIES = [
  {
    id: "agriculture",
    name: "Crop Rotation",
    category: "Agriculture",
    description: "+30% food production.",
    cost: { food: 100, gold: 80 },
    time: 18,
    icon: "Wheat",
  },
  {
    id: "forging",
    name: "Bronze Forging",
    category: "Military",
    description: "+20% army attack.",
    cost: { stone: 100, gold: 140 },
    time: 20,
    icon: "Swords",
  },
  {
    id: "masonry",
    name: "Stone Masonry",
    category: "Construction",
    description: "+40% building health. Unlocks the palace.",
    cost: { wood: 160, stone: 160, gold: 100 },
    time: 22,
    icon: "Landmark",
  },
  {
    id: "trade",
    name: "Caravan Routes",
    category: "Trade",
    description: "+30% gold production.",
    cost: { wood: 100, gold: 180 },
    time: 18,
    icon: "Store",
  },
  {
    id: "armor",
    name: "Reinforced Shields",
    category: "Defense",
    description: "+25% unit defense.",
    cost: { stone: 150, gold: 150 },
    time: 20,
    prerequisite: "forging",
    icon: "Shield",
  },
  {
    id: "engineering",
    name: "Siege Engineering",
    category: "Engineering",
    description: "Unlocks siege workshops and engineers.",
    cost: { wood: 250, stone: 150, gold: 200 },
    time: 28,
    prerequisite: "masonry",
    icon: "Hammer",
  },
  {
    id: "logistics",
    name: "Royal Roads",
    category: "Logistics",
    description: "+25% army movement speed.",
    cost: { wood: 140, stone: 160, gold: 100 },
    time: 22,
    icon: "Route",
  },
  {
    id: "tactics",
    name: "Combined Arms",
    category: "Military",
    description: "Unlocks the military academy and commanders.",
    cost: { food: 180, gold: 250 },
    time: 28,
    prerequisite: "forging",
    icon: "Flag",
  },
  {
    id: "irrigation",
    name: "River Irrigation",
    category: "Agriculture",
    description: "A further +30% food production.",
    cost: { wood: 200, stone: 200, gold: 120 },
    time: 28,
    prerequisite: "agriculture",
    icon: "Droplets",
  },
  {
    id: "fortification",
    name: "Citadel Defenses",
    category: "Defense",
    description: "Watchtowers inflict double damage.",
    cost: { stone: 300, gold: 200 },
    time: 30,
    prerequisite: "masonry",
    icon: "Castle",
  },
  {
    id: "forestry",
    name: "Seasoned Timber",
    category: "Construction",
    description: "+30% wood production.",
    cost: { food: 150, gold: 100 },
    time: 20,
    icon: "Trees",
  },
  {
    id: "mining",
    name: "Deep Mining",
    category: "Engineering",
    description: "+30% stone production.",
    cost: { wood: 180, gold: 120 },
    time: 20,
    icon: "Pickaxe",
  },
  {
    id: "medicine",
    name: "Field Medicine",
    category: "Logistics",
    description: "Friendly armies slowly recover near the capital.",
    cost: { food: 200, gold: 150 },
    time: 24,
    prerequisite: "logistics",
    icon: "Heart",
  },
  {
    id: "steel",
    name: "Tempered Blades",
    category: "Military",
    description: "A further +20% army attack.",
    cost: { stone: 250, gold: 300 },
    time: 35,
    prerequisite: "forging",
    icon: "Sword",
  },
];
const roles = [
  [
    "Legionary",
    "Infantry",
    "Sword",
    120,
    19,
    12,
    2.1,
    1.7,
    1,
    "barracks",
    "Shield wall",
    "Holds the line with a broad shield and a short blade.",
  ],
  [
    "Pike Guard",
    "Spearman",
    "Shield",
    110,
    23,
    10,
    2,
    2.5,
    1.1,
    "barracks",
    "Cavalry breaker",
    "A long-reach formation that counters mounted warriors.",
  ],
  [
    "Longbow",
    "Archer",
    "Crosshair",
    75,
    22,
    4,
    2.3,
    8,
    1.4,
    "archery",
    "Piercing volley",
    "A patient marksman who punishes unprotected flanks.",
  ],
  [
    "Bolt Keeper",
    "Crossbowman",
    "Focus",
    90,
    32,
    6,
    1.8,
    7,
    2,
    "archery",
    "Armor piercing",
    "Heavy bolts trade firing speed for devastating impact.",
  ],
  [
    "Wind Rider",
    "Cavalry",
    "Flag",
    160,
    25,
    10,
    3.9,
    2,
    1.2,
    "stable",
    "Flanking charge",
    "Swift riders close on distant enemies and archers.",
  ],
  [
    "Cataphract",
    "Heavy cavalry",
    "ShieldCheck",
    210,
    30,
    20,
    2.8,
    2,
    1.6,
    "stable",
    "Iron charge",
    "Armored riders excel at breaking infantry lines.",
  ],
  [
    "Oathkeeper",
    "Elite guard",
    "Crown",
    190,
    27,
    23,
    1.8,
    1.8,
    1.2,
    "academy",
    "Unbroken oath",
    "Elite defenders withstand sustained frontal assaults.",
  ],
  [
    "Siege Artisan",
    "Engineer",
    "Hammer",
    130,
    55,
    8,
    1.3,
    10,
    3,
    "siege",
    "Breach",
    "Engineers bring down fortified settlements from afar.",
  ],
  [
    "Marshal",
    "Commander",
    "Star",
    240,
    38,
    18,
    2.5,
    3,
    1.3,
    "academy",
    "Rallying banner",
    "A seasoned officer whose presence inspires nearby troops.",
  ],
];
const names = [
  [
    "Lucan Varro",
    "Titus Corven",
    "Livia Aster",
    "Mara Vey",
    "Cassian Sol",
    "Decimus Orin",
    "Octavia Vale",
    "Felix Tor",
    "Aelius Valerius",
  ],
  [
    "Wei Rong",
    "Lan Mei",
    "Shen Yu",
    "Jin Tao",
    "Hao Feng",
    "Bai Ren",
    "Su Lian",
    "Chen Bo",
    "Liang Zhen",
  ],
  [
    "Daran Ash",
    "Nima Soren",
    "Zara Mehr",
    "Arman Tir",
    "Roya Shad",
    "Cyrus Vah",
    "Mitra Del",
    "Navid Aban",
    "Rostam Ardesh",
  ],
  [
    "Varek Thorn",
    "Brynn Hald",
    "Edda Rook",
    "Osric Wren",
    "Korr Ashen",
    "Bren Mourn",
    "Ylva Frost",
    "Ivar Flint",
    "Ulric Blackthorn",
  ],
  [
    "Wu Keshan",
    "Ren Daku",
    "Xiu Fen",
    "Meng Kai",
    "Zhao Lin",
    "Teng Ru",
    "Bo Shan",
    "Yan Du",
    "Qin Molan",
  ],
  [
    "Azar Voss",
    "Kadir Zol",
    "Nasra Dune",
    "Salim Veyr",
    "Farid Ashkar",
    "Dahir Tarn",
    "Samira Raz",
    "Omar Kesh",
    "Malik Zafir",
  ],
];
export const CHARACTERS = names.flatMap((group, f) =>
  roles.map((r, i) => ({
    id: `unit-${f}-${i}`,
    name: group[i],
    title: r[0],
    class: r[1],
    icon: r[2],
    hp: r[3] + f * 4,
    attack: r[4] + f,
    defense: r[5],
    speed: r[6],
    range: r[7],
    attackSpeed: r[8],
    building: r[9],
    ability: r[10],
    description: r[11],
    faction: [
      "Aurelian Republic",
      "Shen Dynasty",
      "Ashuran Dominion",
      "Ironbound Clans",
      "Crimson Court",
      "Sable Dominion",
    ][f],
    civilization: ["aurelia", "shen", "ashur"][f % 3],
    enemy: f >= 3,
    region: ["Europe", "Asia", "Middle East"][f % 3],
    cost: { food: 55 + i * 15, gold: 20 + i * 12 },
    rank: i > 5 ? "Elite" : i > 3 ? "Veteran" : "Regular",
    upgradePath: ["Recruit", "Veteran", "Champion"],
    appearance: {
      color: ["#709ead", "#91a576", "#cfa15e", "#a8665d", "#926c91", "#c07951"][
        f
      ],
      crest: ["eagle", "lotus", "sun", "wolf", "dragon", "scorpion"][f],
      armor: [
        "bronze cuirass",
        "lamellar armor",
        "scale mail",
        "fur and iron",
        "lacquered plates",
        "desert leathers",
      ][f],
      weapon: r[1],
    },
  })),
);
export const STORY = [
  {
    id: 0,
    title: "The First Standard",
    subtitle: "CHAPTER I · A HOME IN THE VALLEY",
    speaker: "Aelius Valerius",
    dialogue:
      "They left us a banner, a handful of soldiers, and a valley the world had forgotten. We will give our people something more. Not another ruler. A home.",
    objective: "Build a farm and recruit an army.",
    reward: 200,
  },
  {
    id: 1,
    title: "Beyond the River",
    subtitle: "CHAPTER II · THE BROKEN OATH",
    speaker: "Livia Aster",
    dialogue:
      "The Ironbound have crossed the river. Their chieftain once swore to protect these roads. Now our merchants hang from his gates. The oath is broken. We must open the road ourselves.",
    objective: "Capture the Riverwatch outpost.",
    reward: 350,
  },
  {
    id: 2,
    title: "A Crown of Ash",
    subtitle: "CHAPTER III · THE PRICE OF PEACE",
    speaker: "Aelius Valerius",
    dialogue:
      "Blackthorn offers us peace, if we kneel. I have seen his peace: burned fields and empty houses. Tonight we march, not for a crown, but for everyone who cannot.",
    objective: "Conquer the Iron Citadel.",
    reward: 600,
  },
];
export const DEFAULT_SETTINGS = {
  music: 25,
  sound: 50,
  graphics: "High",
  camera: 50,
  notifications: true,
  reducedMotion: false,
  showHealth: true,
  language: "English",
};
